version: "3.8"
services:
  mysql:
    image: mysql:8.0.34
    container_name: shopping-mysql
    restart: always
    ports:
      - '3306:3306'
    environment:
      - MYSQL_ROOT_PASSWORD=1234
    volumes:
      - ./mysql/initdb.d:/docker-entrypoint-initdb.d
    deploy:
      resources:
        limits:
          memory: 1G
        reservations:
          memory: 512M