services:
  mysql:
    image: mysql:8.0
    container_name: spring-shopping-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: spring_shopping
      MYSQL_USER: shopping
      MYSQL_PASSWORD: shopping
    ports:
      - "3306:3306"
