spring:
  application:
    name: spring-shopping
  datasource:
    url: jdbc:h2:mem:spring-shopping;MODE=MySQL;DB_CLOSE_DELAY=-1
    username: sa
    password: ""
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false

app:
  auth:
    jwt-secret: ${JWT_SECRET:qwpWIyUDDe9xAAVPDgCXdzA4neO213WBgV3OjERKsWtp/1g/PYFSdyG8/rvhJ7PnAsCSJE99w3gp7q5vZcwzgg}
    token-validity-minutes: 30
