spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/coreDB
    username: root
    password: 1234
    hikari:
      maximum-pool-size: 5
      pool-name: core-db-pool
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        show_sql: true

  flyway:
    enabled: false
    locations: classpath:db/migration
