spring.application.name=spring-shopping

spring.datasource.url=jdbc:mysql://localhost:3306/spring_shopping
spring.datasource.username=shopping
spring.datasource.password=shopping
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=validate
spring.flyway.enabled=false

jwt.secret=spring-shopping-secret-key-must-be-at-least-256-bits-long
jwt.expiration-ms=3600000
