spring.application.name=spring-shopping

# MySQL
spring.datasource.url=jdbc:mysql://localhost:3306/shopping
spring.datasource.username=shopping
spring.datasource.password=shopping
spring.jpa.hibernate.ddl-auto=validate

# Flyway
spring.flyway.enabled=true

# Transaction logging
logging.level.org.springframework.transaction.interceptor=TRACE

# Connection pool logging
logging.level.com.zaxxer.hikari=DEBUG

# SQL logging
logging.level.org.hibernate.SQL=DEBUG
