### 회원 가입
POST localhost:8080/members
Content-Type: application/json

{
  "email": "test@gmail.com",
  "password": "password"
}

### 로그인
POST localhost:8080/login
Content-Type: application/json

{
  "email": "test@gmail.com",
  "password": "password"
}